.Dd October 24, 2022
.Dt TRIGGERD 8
.Sh NAME
.Nm triggerd
.Nd UDP-based scheduler with a single slot queue
.Sh SYNOPSIS
.Nm
.Ar cmd ...
.Sh DESCRIPTION
The
.Nm
utility processes files ...
.Sh ENVIRONMENT
.Bl -tag -width TRIGGERD_PORT
.It Ev TRIGGERD_PORT
UDP port to listen on. Defaults to 51161.
.Sh EXIT STATUS
.Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr trigger 1
.Sh AUTHORS
Written by
.An Yana Luna-Terra Aq Mt yana@riseup.net .
.\" .Sh CAVEATS
